version: '3.8'
volumes:
  apim:
    driver: local
services:
  apim:
    build: ./dockerfiles/apim
    container_name: api-manager-ad-test
    ports:
      - 9443:9443
      - 8243:8243
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9443" ]
      interval: 10s
      start_period: 180s
      retries: 20